include:
  #- board: bmp_boost
  #  shield: torabo_tsuki_lp_left
  #  snippet: "studio-rpc-usb-uart split-central input-trackball input-listener"
  #  artifact-name: torabo_tsuki_lp_left_central
  # - board: bmp_boost
  #   shield: torabo_tsuki_lp_right
  #   snippet: studio-rpc-usb-uart
  #   artifact-name: torabo_tsuki_lp_right_peripheral
  - board: bmp_boost
    shield: torabo_tsuki_lp_left
    snippet: studio-rpc-usb-uart
    artifact-name: left_peripheral
  - board: bmp_boost
    shield: torabo_tsuki_lp_left
    snippet: "studio-rpc-usb-uart encoder encoder-left"
    artifact-name: left_peripheral_encoder
  - board: bmp_boost
    shield: torabo_tsuki_lp_left
    snippet: "zmk-usb-logging encoder encoder-left"
    cmake-args: -DCONFIG_ZMK_LOG_LEVEL_DBG=y -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=5000
    artifact-name: left_peripheral_encoder_debug
  - board: bmp_boost
    shield: torabo_tsuki_lp_right
    snippet: "studio-rpc-usb-uart split-central input-trackball input-listener"
    artifact-name: right_central
  - board: bmp_boost
    shield: torabo_tsuki_lp_right
    snippet: "studio-rpc-usb-uart split-central input-trackball input-listener encoder"
    artifact-name: right_central_encoder
  - board: bmp_boost
    shield: torabo_tsuki_lp_left
    snippet: "studio-rpc-usb-uart input-trackball input-split"
    artifact-name: torabo_tsuki_lp_double_ball_left_peripheral
  - board: bmp_boost
    shield: torabo_tsuki_lp_right
    snippet: "studio-rpc-usb-uart split-central input-trackball input-listener input-split-listener"
    artifact-name: torabo_tsuki_lp_double_ball_right_central
  - board: bmp_boost
    shield: settings_reset