CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_CDC_ACM_BOOTLOADER_TRIGGER=y
CONFIG_ZMK_STATUS_LED=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=9000000
CONFIG_ZMK_NON_LIPO_MIN_MV=1000
CONFIG_ZMK_NON_LIPO_LOW_MV=900

#CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
CONFIG_ZMK_INPUT_PROCESSOR_TEMP_LAYER=y

# Enable BLE Management Module
CONFIG_ZMK_BLE_MANAGEMENT=y
# Enable Studio custom RPC features
CONFIG_ZMK_BLE_MANAGEMENT_STUDIO_RPC=y
